import React from 'react';
// Import Bootstrap first (ensure bootstrap CSS is in your index.js)
import 'bootstrap/dist/css/bootstrap.min.css';
import { 
  Box, 
  Typography, 
  Chip, 
  Paper, 
  IconButton, 
  Divider,
  Tooltip
} from '@mui/material';
import DownloadIcon from '@mui/icons-material/Download';
import RefreshIcon from '@mui/icons-material/Refresh';
import InfoOutlinedIcon from '@mui/icons-material/InfoOutlined';
import { BorderBottom } from '@mui/icons-material';

// Color Constants
const PATENT_ORANGE = '#F04E23';
const SOFT_RED_BG = 'rgba(240, 78, 35, 0.05)';
const PARTIAL_YELLOW = '#FFF9C4';
const CONSIDERABLE_GREEN = '#E8F5E9';

const data = [
  {
    feature: "Automatically extracting symbolic rules from the internal representations of said neural modules.",
    result: "The US11049043B2 describes a method for extracting symbolic rules from a black-box model. However, this is achieved through a pedagogical, model-agnostic approach by analyzing the model's input-output behavior using perturbed data...",
    overlap: "Partial",
    overlapColor: "#FBC02D"
  },
  {
    feature: "Training said neural modules using constraints derived from symbolic logic, wherein the logic provides a framework for the training process.",
    result: "The US11049043B2 discloses an entirely post-hoc method. It takes an existing, pre-trained black-box model as its starting input and proceeds to extract a new, explainable white-box model from it. There is no mention of training...",
    overlap: "-",
    overlapColor: "#94a3b8"
  },
  {
    feature: "An explainability pipeline generated by said method, wherein: The pipeline utilizes the extracted symbolic rules to provide explanations for the outputs of the neural modules.",
    result: "The primary objective of the US11049043B2 is to generate an explainable 'white-box AI model' from an unexplainable black-box one. This white-box model is explicitly described as being composed of a set of symbolic rules...",
    overlap: "Considerable",
    overlapColor: "#2e7d32"
  }
];

const OverlapMatrix = () => {
  return (
    <div className="container-fluid bg-light min-vh-100 py-5 " style={{marginTop:'60px'}}>
      <div className="container">
        
        {/* HEADER SECTION */}
        <div className="row align-items-center mb-4">
          <div className="col-md-8 ">
            <Typography variant="h4" fontWeight="800" sx={{ color: '#1e293b', marginBottom:'20px' }}>
              Analysis <span style={{ color: PATENT_ORANGE }}>Report</span>
            </Typography>
            <Typography variant="body2" color="text.secondary">
              Comparison: <Chip label="US11049043B2" size="small" variant="outlined" sx={{ ml: 1 }} />
            </Typography>
          </div>
          
          {/* Action Buttons from your Image */}
          <div className="col-md-4 d-flex justify-content-md-end gap-2 mt-3 mt-md-0">
            {/* <IconButton sx={{ 
              border: '1.5px solid #cbd5e1', 
              borderRadius: '12px', 
              color: '#64748b',
              width: '45px', height: '45px'
            }}>
              <RefreshIcon />
            </IconButton> */}
            <IconButton sx={{ 
              border: `1.5px solid ${PATENT_ORANGE}`, 
              borderRadius: '12px', 
              bgcolor: SOFT_RED_BG,
              color: PATENT_ORANGE,
              width: '45px', height: '45px'
            }}>
              <DownloadIcon />
            </IconButton>
          </div>
        </div>

        {/* DATA TABLE / GRID */}
        <Paper elevation={0} sx={{ border: '1px solid #ced0d1ff', borderRadius: '16px', overflow: 'hidden' }}>
          {/* Table Header (Hidden on Mobile) */}
          <div className="row g-0 d-none d-md-flex bg-white border-bottom  py-3 px-4">
            <div className="col-3"><Typography fontWeight="bold" variant="subtitle2" style={{ color: PATENT_ORANGE }} >KEY FEATURE</Typography></div>
            <div className="col-7 text-center"><Typography fontWeight="bold" variant="subtitle2" style={{ color: PATENT_ORANGE }}>SEARCH RESULT</Typography></div>
            <div className="col-2 text-end"><Typography fontWeight="bold" variant="subtitle2" style={{ color: PATENT_ORANGE }}>OVERLAP</Typography></div>
          </div>

          {/* Rows */}
          {data.map((item, index) => (
            <div key={index} className="row g-0 border-bottom align-items-stretch bg-white" >
              {/* Feature */}
              <div className="col-md-3 p-4 border-end-md" style={{ backgroundColor: '#fafafa' }}>
                <Typography variant="body2" fontWeight="600" color="#334155">
                  {item.feature}
                </Typography>
              </div>

              {/* Result */}
              <div className="col-md-7 p-4">
                <Typography variant="body2" color="#475569" sx={{ lineHeight: 1.7 }}>
                  {item.result}
                </Typography>
              </div>

              {/* Overlap Status */}
              <div className="col-md-2 p-4 d-flex align-items-start justify-content-md-end">
                <Chip 
                  label={item.overlap} 
                  sx={{ 
                    fontWeight: '700',
                    borderRadius: '6px',
                    bgcolor: item.overlap === 'Considerable' ? CONSIDERABLE_GREEN : 
                             item.overlap === 'Partial' ? PARTIAL_YELLOW : '#f1f5f9',
                    color: item.overlapColor,
                    minWidth: '100px'
                  }} 
                />
              </div>
            </div>
          ))}
        </Paper>

        {/* RELEVANT EXCERPTS SECTION */}
        <Box sx={{ mt: 4 }}>
          <Box className="d-flex align-items-center mb-2">
            <InfoOutlinedIcon sx={{ fontSize: 18, color: PATENT_ORANGE, mr: 1 }} />
            <Typography variant="subtitle2" fontWeight="bold" sx={{ letterSpacing: 1, color: '#64748b' }}>
              RELEVANT EXCERPTS
            </Typography>
          </Box>
          <Paper elevation={0} sx={{ 
            p: 3, 
            borderRadius: '12px', 
            bgcolor: '#f8fafc', 
            border: '1px dashed #b9bdc0ff' 
          }}>
            <Typography variant="body2" fontStyle="italic" color="#475569">
              "The prior art discloses a pedagogical approach to rule extraction, treating the source model as a black box rather than analyzing its internal representations: 'Other rule extraction methods may instead employ pedagogical techniques, which may be applied to any black-box model regardless of internal components...'"
            </Typography>
          </Paper>
        </Box>
      </div>
    </div>
  );
};

export default OverlapMatrix;